Solve differential eqution dy/dx = 1 + y/x ; 1≤x≤6 , x(1) = 1 by using RK method
of 4th order with step size h = 1

f(x,y) := 1 + y/x;
x0 : 1.0;
y0 : 1.0;
h : 1;
array(yn, flonum, 5)$

for i : 1 thru 5 do (
k1 : h*f(x0, y0),
k2 : h*f(x0 + h/2, y0 + k1/2),
k3 : h*f(x0 + h/2, y0 +k2/2),
k4 : h*f(x0 + h, y0 + k3),
slope : (1/6)*(k1 + 2*k2 + 2*k3 + k4),
yn[i] : y0 + slope,
y0 : yn[i],
x0 : x0 + h, print("Step", i, "=", yn[i])
)$
