Find the integration of f(x) = 1/x in [1, 2] by using
trapezoidal'rule Method

f(x) := 1/x;
a : 1;
b : 2;
h : b - a;

i1 : float((h / 2) * (f(a) + f(b)));
i : float(integrate(f(x), x, a, b));

er : abs(i - i1);



Find the integration of f(x) = 1/(1 + X^2) in [0, 1] by using
trapezoidal'rule Method.

f(x) := 1 / (1 + x^2);
a : 0;
b : 1;
h : b - a;

i1 : float((h / 2) * (f(a) + f(b)));
i : float(integrate(f(x), x, a, b));
er : abs(i - i1);
